description = "Ubuntu bionic base image with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.13.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.1.36-base-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "index.docker.io/paketobuildpacks/run:base-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:base-cnb"]
